# Generated by Django 4.1.2 on 2022-12-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='about_blog',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
