# Generated by Django 4.1.2 on 2022-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Culture', 'Culture'), ('Sport', 'Sport'), ('Food', 'Food'), ('Politics', 'Politics'), ('Celebrity', 'Celebrity'), ('Startups', 'Startups'), ('Travel', 'Travel')], max_length=200),
        ),
    ]
