# Generated by Django 4.1.5 on 2023-01-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='about_blog',
            new_name='description',
        ),
    ]
